name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/develop') && 'Staging' || github.event_name == 'push' && startsWith(github.ref, 'refs/heads/uat') && 'UAT' || 'Preview' }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --git-branch=${{ env.BRANCH }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project & Generate Prisma Client Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
