name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main
      - develop
      - uat

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/develop') && 'Staging' || github.event_name == 'push' && startsWith(github.ref, 'refs/heads/uat') && 'UAT' || 'Preview' }}
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          mv .vercel/.env.preview.local .env

      - name: Yarn Build Test
        run: |
          npm install -g yarn
          yarn
          yarn prisma generate
          yarn run build
