name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add Additional Environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .vercel/.env.production.local
          echo "GCS_BUCKET=${{ secrets.GCS_BUCKET }}" >> .vercel/.env.production.local
          echo "GCS_CLIENT_EMAIL=${{ secrets.GCS_CLIENT_EMAIL }}" >> .vercel/.env.production.local
          echo "GCS_PRIVATE_KEY=${{ secrets.GCS_PRIVATE_KEY }}" >> .vercel/.env.production.local
          echo "GCS_PROJECT_ID=${{ secrets.GCS_PROJECT_ID }}" >> .vercel/.env.production.local

      - name: Build Project & Generate Prisma Client Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
